### ISSUE TITLE
Issue with doctest result containing escaped backslashes

### ISSUE THREAD

**Issue by etienneschalk** [max-sixty/pytest-accept#147]
When a doctest result contains escaped backslashes, after a run of pytest-accept, they are not escaped anymore

![Screenshot from 2024-02-05 23-52-23](https://github.com/max-sixty/pytest-accept/assets/45271239/a88db007-7ead-46fd-bf3c-c96dc64ac6f2)

Potential solution according to the README: use a raw string as a docstring

**Comment by max-sixty** [comment]
Yes, this is covered in the Readme by using a raw docstring...

If there are better approach, I'm very open to those...
